name: Build and test

on:
  pull_request:
    paths:
      - Vienna*/**
      - External/**
      - Scripts/**
      - Makefile
      - .github/workflows/*

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-13
            xcode: /Applications/Xcode_15.2.app/Contents/Developer
          - os: macos-14
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: ${{ matrix.xcode }}
    timeout-minutes: 15

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build Xcode project
      run: |
        xcodebuild -version
        xcodebuild build-for-testing -project Vienna.xcodeproj -scheme Vienna -configuration Development | xcpretty && exit ${PIPESTATUS[0]}
    - name: Test Xcode project
      run: |
        xcodebuild -version
        xcodebuild test -project Vienna.xcodeproj -scheme Vienna -configuration Development | xcpretty && exit ${PIPESTATUS[0]}
